version: "3.8"
services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        restart: always
        command: >
            sh -c "gunicorn monitoring.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - static_data:/app/static
            - media_data:/app/media
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
    nginx:
        build: ./nginx
        restart: always
        ports:
            - 1337:80
        volumes:
          - static_data:/app/static
          - media_data:/app/mediac
        depends_on:
          - web

volumes:
    postgres_data:
    static_data:
    media_data:
