version: '3.8'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: gunicorn monitoring.wsgi:application --bind 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - db
        volumes:
          - .:/app
          - static_data:/app/static
          - media_data:/app/media
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        volumes:
          - static_data:/app/static
          - media_data:/app/media
        depends_on:
          - web

volumes:
    postgres_data:
    static_data:
    media_data: