version: "3.8"
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
            - static_data:/app/static
            - media_data:/app/media
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - ./.env.dev
    db:
        image: postgres:13
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database

volumes:
    postgres_data:
    static_data:
    media_data:
